language: r
r:
  - release
  - devel
sudo: false
warnings_are_errors: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - R -e 'install.packages(c("remotes", "knitr", "rmarkdown", "fansi", "NMF", "flexclust", "pbapply", "matrixStats", "mlbench", "ranger"))'

install:
  - R -e 'remotes::install_deps(dep = NA)'
