language: r
r:
  - release
  - devel
sudo: false
warnings_are_errors: false
cache: packages
r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - R -e 'install.packages(c("remotes", "knitr"))'

install:
  - R -e 'remotes::install_deps(dep = NA)'
