language: r
r:
  - release
  - devel
sudo: false
warnings_are_errors: false
cache: packages

env:
  global:
    - R_BUILD_ARGS=" --no-build-vignettes --no-manual "
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
  - R -e 'install.packages(c("remotes", "knitr"))'

install:
  - R -e 'remotes::install_deps(dep = NA)'
